### ISSUE TITLE
Error Message / Information

### ISSUE THREAD

**Issue by OvisMaximus** [ryanfox1985/OctoPrint-Youtube-Timelapse#17]
I just installed and configured the plugin and also used the initial upload functionality provided below the line "Here you can upload your previous videos already stored at:".

Strange thing is that it transferred eight videos of about 50 successfully to youtube but seems to ignore the rest.

After some retries I had a look at the logs:
`
2021-03-13 13:57:08,802 - googleapiclient.http - WARNING - Encountered 403 Forbidden with reason "quotaExceeded"
2021-03-13 13:57:08,803 - octoprint.server.api - ERROR - Error while executing SimpleApiPlugin youtube_timelapse
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/server/api/__init__.py", line 146, in pluginCommand
    response = api_plugin.on_api_command(command, data)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1890, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_youtube_timelapse/__init__.py", line 163, in on_api_command
    self.upload_timelapse(entry.path, data['upload_videos_delete_after'])
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_youtube_timelapse/__init__.py", line 247, in upload_timelapse
    _status, response = insert_request.next_chunk()
  File "/home/pi/oprint/lib/python3.7/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/googleapiclient/http.py", line 1004, in next_chunk
    raise ResumableUploadError(resp, content)
googleapiclient.errors.ResumableUploadError: <HttpError 403 when requesting None returned "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.". Details: "The request cannot be completed because you have exceeded your <a href="/youtube/v3/getting-started#quota">quota</a>.">
2021-03-13 13:57:08,812 - tornado.access - ERROR - 500 POST /api/plugin/youtube_timelapse (::ffff:10.10.60.2) 564.05ms
`

It would be helpful when such a problem would be transparent to me as a user, like by telling me about the exceeded quota message from youtube.

(BTW: Any idea why my quota is exceeded after successfully uploading only eight videos?)

**Comment by spence572** [comment]
Hi, I am having the same issue but instead, it hasn't uploaded any videos. Do you have any idea?
Thanks

Paul

**Comment by andcam** [comment]
getting exactly the same here. used 10 of 10,000 quota limit, so that's not the problem.

**Comment by spijkermenno** [comment]
is this fixed? i'm getting this error right now. uploaded a few and now it gives this error.
